#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jan 25, 2018 01:34:38 AM
import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1

from inventory.views import additem_support
from inventory.backend import models


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    additem_support.set_Tk_var()
    top = Add_Item(root)
    additem_support.init(root, top)
    root.mainloop()


w = None


def create_Add_Item(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    additem_support.set_Tk_var()
    top = Add_Item(w)
    additem_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Add_Item():
    global w
    w.destroy()
    w = None


class Add_Item:
    def addItem(self):
        try:
            itemname = additem_support.productname.get()
            itembarcode = additem_support.barcode.get()
            price = float(additem_support.price.get())
            item = models.Item(name=itemname, price=price)
            saved = item.save(insert=True)
            if saved == 1:
                messagebox.showinfo(title="Success", message="Item {} added successfully".format(itemname))

                self.barcode.delete(0, END)
                self.price.delete(0, END)
                self.productname.delete(0, END)
                self.productname.focus()
            else:
                messagebox.showinfo(title="Failed", message="Couldnot add {}".format(itemname))
        except ValueError:
            messagebox.showinfo(title="Warning", message="Price must be a Number")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'
        font10 = "-family {Segoe UI} -size 20 -weight bold -slant " \
                 "roman -underline 0 -overstrike 0"

        top.geometry("600x454+477+165")
        top.title("Add Item")
        top.configure(background="#ffddcc")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.productname = Entry(top)
        self.productname.place(relx=0.28, rely=0.2, relheight=0.07
                               , relwidth=0.39)
        self.productname.configure(background="white")
        self.productname.configure(disabledforeground="#a3a3a3")
        self.productname.configure(font="TkFixedFont")
        self.productname.configure(foreground="#000000")
        self.productname.configure(highlightbackground="#d9d9d9")
        self.productname.configure(highlightcolor="black")
        self.productname.configure(insertbackground="black")
        self.productname.configure(selectbackground="#c4c4c4")
        self.productname.configure(selectforeground="black")
        self.productname.configure(textvariable=additem_support.productname)

        self.barcode = Entry(top)
        self.barcode.place(relx=0.28, rely=0.31, relheight=0.07, relwidth=0.39)
        self.barcode.configure(background="white")
        self.barcode.configure(disabledforeground="#a3a3a3")
        self.barcode.configure(font="TkFixedFont")
        self.barcode.configure(foreground="#000000")
        self.barcode.configure(highlightbackground="#d9d9d9")
        self.barcode.configure(highlightcolor="black")
        self.barcode.configure(insertbackground="black")
        self.barcode.configure(selectbackground="#c4c4c4")
        self.barcode.configure(selectforeground="black")
        self.barcode.configure(textvariable=additem_support.barcode)

        self.price = Entry(top)
        self.price.place(relx=0.28, rely=0.42, relheight=0.07, relwidth=0.39)
        self.price.configure(background="white")
        self.price.configure(disabledforeground="#a3a3a3")
        self.price.configure(font="TkFixedFont")
        self.price.configure(foreground="#000000")
        self.price.configure(highlightbackground="#d9d9d9")
        self.price.configure(highlightcolor="black")
        self.price.configure(insertbackground="black")
        self.price.configure(selectbackground="#c4c4c4")
        self.price.configure(selectforeground="black")
        self.price.configure(textvariable=additem_support.price)

        self.addbtn = Button(top)
        self.addbtn.place(relx=0.38, rely=0.66, height=44, width=117)
        self.addbtn.configure(activebackground="#d9d9d9")
        self.addbtn.configure(activeforeground="#000000")
        self.addbtn.configure(background="#009933")
        self.addbtn.configure(disabledforeground="#a3a3a3")
        self.addbtn.configure(font="Bold")
        self.addbtn.configure(foreground="#fff")
        self.addbtn.configure(highlightbackground="#d9d9d9")
        self.addbtn.configure(highlightcolor="black")
        self.addbtn.configure(pady="0")
        self.addbtn.configure(text='''ADD''')
        self.addbtn.configure(command=self.addItem)

        self.productname_lbl = Label(top)
        self.productname_lbl.place(relx=0.08, rely=0.2, height=21, width=83)
        self.productname_lbl.configure(background="#ffddcc")
        self.productname_lbl.configure(disabledforeground="#a3a3a3")
        self.productname_lbl.configure(foreground="#000000")
        self.productname_lbl.configure(text='''Product Name''')

        self.barcode_lbl = Label(top)
        self.barcode_lbl.place(relx=0.13, rely=0.31, height=21, width=49)
        self.barcode_lbl.configure(background="#ffddcc")
        self.barcode_lbl.configure(disabledforeground="#a3a3a3")
        self.barcode_lbl.configure(foreground="#000000")
        self.barcode_lbl.configure(text='''Barcode''')

        self.price_lbl = Label(top)
        self.price_lbl.place(relx=0.12, rely=0.42, height=21, width=63)
        self.price_lbl.configure(background="#ffddcc")
        self.price_lbl.configure(disabledforeground="#a3a3a3")
        self.price_lbl.configure(foreground="#000000")
        self.price_lbl.configure(text='''Price in USD''')

        self.additem_lbl = Label(top)
        self.additem_lbl.place(relx=0.33, rely=0.04, height=43, width=126)
        self.additem_lbl.configure(background="#ffddcc")
        self.additem_lbl.configure(disabledforeground="#a3a3a3")
        self.additem_lbl.configure(font=font10)
        self.additem_lbl.configure(foreground="#000000")
        self.additem_lbl.configure(text='''Add Item''')


if __name__ == '__main__':
    vp_start_gui()
