#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 16, 2018 10:15:26 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1

from views import categories_support
from views import additem


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Categories(root)
    categories_support.init(root, top)
    root.mainloop()


w = None


def create_Categories(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = Categories(w)
    categories_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Categories():
    global w
    w.destroy()
    w = None


class Categories:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        # _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        # _fgcolor = '#000000'  # X11 color: 'black'
        # _compcolor = '#d9d9d9' # X11 color: 'gray85'
        # _ana1color = '#d9d9d9' # X11 color: 'gray85'
        # _ana2color = '#d9d9d9' # X11 color: 'gray85'
        # self.style = ttk.Style()
        # if sys.platform == "win32":
        #     self.style.theme_use('winnative')
        # self.style.configure('.',background=_bgcolor)
        # self.style.configure('.',foreground=_fgcolor)
        # self.style.configure('.',font="TkDefaultFont")
        # self.style.map('.',background=
        #     [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+450+127")
        top.title("Categories")
        top.configure(background="#d9d9d9")

        self.shampoo = ttk.Button(top)
        self.shampoo.place(relx=0.12, rely=0.13, height=75, width=106)
        self.shampoo.configure(takefocus="")
        self.shampoo.configure(text='''Shampoo''')
        self.shampoo.configure(width=106)
        self.shampoo.configure(command=self.shampoo_action)

        self.haircolor = ttk.Button(top)
        self.haircolor.place(relx=0.37, rely=0.13, height=75, width=106)
        self.haircolor.configure(takefocus="")
        self.haircolor.configure(text='''Hair color''')
        self.haircolor.configure(command=self.haircolor_action)

        self.conditioner = ttk.Button(top)
        self.conditioner.place(relx=0.63, rely=0.13, height=75, width=106)
        self.conditioner.configure(takefocus="")
        self.conditioner.configure(text='''Conditioner''')
        self.conditioner.configure(command=self.conditioner_action)

        self.skincare = ttk.Button(top)
        self.skincare.place(relx=0.12, rely=0.44, height=75, width=106)
        self.skincare.configure(takefocus="")
        self.skincare.configure(text='''Skin Care''')
        self.skincare.configure(command=self.skincare_action)


        self.misc = ttk.Button(top)
        self.misc.place(relx=0.37, rely=0.44, height=75, width=106)
        self.misc.configure(takefocus="")
        self.misc.configure(text='''Misc''')
        self.misc.configure(command=self.misc_action)

        self.Services = ttk.Button(top)
        self.Services.place(relx=0.63, rely=0.44, height=75, width=106)
        self.Services.configure(takefocus="")
        self.Services.configure(text='''Services''')
        self.Services.configure(command=self.service)

    def service(self):
        w.destroy()
        additem.vp_start_gui(category="service")

    def misc_action(self):
        w.destroy()
        additem.vp_start_gui(category="service")

    def skincare_action(self):
        w.destroy()
        additem.vp_start_gui(category="skincare")

    def conditioner_action(self):
        w.destroy()
        additem.vp_start_gui(category="conditioner")

    def haircolor_action(self):
        w.destroy()
        additem.vp_start_gui(category="haircolor")

    def shampoo_action(self):
        w.destroy()
        additem.vp_start_gui(category="shampoo")


if __name__ == '__main__':
    vp_start_gui()
