#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jan 24, 2018 03:35:42 PM
import sys


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1

from inventory.views import salespage_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1(root)
    salespage_support.init(root, top)
    root.mainloop()


w = None


def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = New_Toplevel_1(w)
    salespage_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("600x450+488+165")
        top.title("New Toplevel 1")
        top.configure(background="#ffddcc")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.18, rely=0.11, relheight=0.34, relwidth=0.64)
        self.TFrame1.configure(relief=SUNKEN)
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief=SUNKEN)
        self.TFrame1.configure(width=385)

        self.Entry1 = Entry(self.TFrame1)
        self.Entry1.place(relx=0.13, rely=0.13, relheight=0.19, relwidth=0.43)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Button1 = Button(self.TFrame1)
        self.Button1.place(relx=0.7, rely=0.13, height=24, width=76)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#006666")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#fff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Scan''')

        self.Button2 = Button(self.TFrame1)
        self.Button2.place(relx=0.39, rely=0.65, height=24, width=79)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#003d99")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#fff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Sell''')

        self.menubar = Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.48, rely=0.02, height=19, width=1)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Tlabel''')

        self.TLabel2 = ttk.Label(top)
        self.TLabel2.place(relx=0.44, rely=0.0, height=42, width=84)
        self.TLabel2.configure(background="#ffddcc")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="bold 25")
        self.TLabel2.configure(relief=FLAT)
        self.TLabel2.configure(anchor=CENTER)
        self.TLabel2.configure(text='''Sales''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.2, rely=0.73, height=44, width=117)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#00802b")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#fff")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Add Item''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.63, rely=0.73, height=44, width=107)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#005c99")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#fff")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Reports''')


if __name__ == '__main__':
    vp_start_gui()
